import { Cormorant_Garamond, Jost } from "next/font/google";
import "./globals.css";
const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
});

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});


export const metadata = {
  title: "Royal BBQ Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${jost.variable} ${cormorantGaramond.variable} h-full antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
